Models/CaricaFile.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
namespace GNSShare_client.Models;

public class CaricaFileModel
{
    public List<SelectListItem> ListaStazioni { get; set; }
    [Required]
    public string codiceStazione { get; set; }
    
    [RegularExpression(@"^\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}$")]
    [Required]
    public string dataCreazione { get; set; }

    [Required]
    [RegularExpression(@"^[0-9]*(?:[\.,][0-9]*)?$")]
    public string frequenza { get; set; }

    [RegularExpression(@"^\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}$")]
    [Required]
    public string inizioPeriodo { get; set; }

    [RegularExpression(@"^\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}$")]
    [Required]
    public string finePeriodo { get; set; }

    public string nomeFile { get; set; }
    public string percorsoFile { get; set; }

    [Required]
    public IFormFile file { get; set; }
}

Models/Mappa.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
namespace GNSShare_client.Models;

public class MappaModel
{
    public Dictionary<string, client.Stazione>? ListaStazioni { get; set; }
    public string stazioneScelta { get; set; }
    public client.Stazione _stazioneScelta { get; set; }

    //public List<SelectListItem> ListaFile { get; set; }
    public string fileScelto { get; set; }
}

Controllers/MappaController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using GNSShare_client.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace GNSShare_client.Controllers;

public class MappaController : Controller
{
    public string FORM_NON_VALIDO = "Il form non è compilato correttamente";
    //static public string previousAction = "";
    static public Dictionary<string, client.Stazione>? ListaStazioni;
    static public bool aggiuntaNuovaStazione = false;
    static public bool aggiuntoNuovoFile = false;
    static public string? SourceMappaStazioni;
    static public bool aggiornaMappaStazioni = true;

    public delegate void EventHandler(object sender, EventArgs e);
    public delegate Task<IActionResult> EventHandler_Controller(Controller ctr, object sender, System.Net.IPAddress? ip, EventArgs e);
    public delegate object? EventHandler_IP(object sender, System.Net.IPAddress? ip, EventArgs e);


    static public event EventHandler? InvocatoUploadFile;
    static public event EventHandler_IP? InvocatoGetElencoStazioni, InvocatoGetStazioni, InvocatoLoadFile, InvocatoGetMappaStazioni, InvocatoGetSingolaMappaStazione;
    static public event EventHandler_Controller? InvocatoDownloadFile;

    private readonly ILogger<MappaController> _logger;
    public static System.Net.IPAddress? remoteIpAddress;

    public MappaController(ILogger<MappaController> logger)
    {
        _logger = logger;
    }


    public IActionResult CaricaFile(CaricaFileModel model, EventArgs e)
    {
        List<client.Stazione>? elencoStazioni = (List<client.Stazione>?)InvocatoGetStazioni?.Invoke(model, Request.HttpContext.Connection.RemoteIpAddress, e);
        var stazioni = new List <SelectListItem> ();
        if (elencoStazioni is not null)
            foreach( client.Stazione elem in elencoStazioni)
                stazioni.Add(new SelectListItem {Value = elem.codice, Text = elem.codice});
        
        model.ListaStazioni = stazioni;

        ViewBag.ipAddress = Request.HttpContext.Connection.RemoteIpAddress;
        return View(model);  
    }

    public async Task<IActionResult> LoadFile(CaricaFileModel model, EventArgs e)
    {
        ViewBag.ipAddress = Request.HttpContext.Connection.RemoteIpAddress;
        try
        {
            ModelState.Remove("ListaStazioni"); //al ritorno dalla view questo attributo viene resettato, quindi lo escludo dalla validazione
            ModelState.Remove("nomeFile");
            ModelState.Remove("percorsoFile");
            if(ModelState.IsValid)
            {
                if( model.file == null || model.file.Length == 0) throw new Exception("File non corretto.");
            
                string? nomeFile = (string?)InvocatoLoadFile?.Invoke(model, Request.HttpContext.Connection.RemoteIpAddress, e);
                model.nomeFile = nomeFile;

                InvocatoUploadFile?.Invoke(model, e); //commentare quando saranno risolti i problemi del server di scrittura su file
                
                TempData["SuccessMessage"] = "Nuovo file caricato a sistema! Il nuovo file si chiama " + nomeFile;
                return RedirectToAction("CaricaFile");
            }
            throw new Exception(FORM_NON_VALIDO);
        }
        catch(Exception ex)
        {
            ExceptionHandler(ex.Message);
        }
        
        return RedirectToAction("CaricaFile", model);
    }

    public IActionResult MappaStazioni(MappaModel model, EventArgs e)
    {
        if(aggiornaMappaStazioni)
        {
            SourceMappaStazioni = (string?)InvocatoGetMappaStazioni?.Invoke(model, Request.HttpContext.Connection.RemoteIpAddress, e);
            aggiornaMappaStazioni = false;
        }
        ViewBag.MapStationsData = SourceMappaStazioni;
        
        //ViewBag.MapStationsData = SourceMappaStazioni;
        try
        {            
            if(ListaStazioni is null || ListaStazioni.Count() == 0 || aggiuntaNuovaStazione || aggiuntoNuovoFile) 
            {
                
                //SourceMappaStazioni = ViewBag.MapStationsData; //così al prossimo refresh la mappa non deve essere ricaricata

                ListaStazioni = new Dictionary<string, client.Stazione>();
                foreach( client.Stazione st in (List<client.Stazione>?)InvocatoGetElencoStazioni?.Invoke(model, Request.HttpContext.Connection.RemoteIpAddress, e))
                {
                    st.popolaElencoFileCaricati();
                    ListaStazioni.Add(st.codice, st);
                } 
            
                aggiuntaNuovaStazione = false;
                aggiuntoNuovoFile = false;
                
            }
            model.ListaStazioni = ListaStazioni;
            
            if(model.stazioneScelta is not null)
            {
                model._stazioneScelta = ListaStazioni[model.stazioneScelta];
                ViewBag.MapSingleStationData = InvocatoGetSingolaMappaStazione?.Invoke(model, Request.HttpContext.Connection.RemoteIpAddress, e);
            }

        }
        catch(Exception ex)
        {
            ExceptionHandler(ex.Message);
        }
        ViewBag.ipAddress = Request.HttpContext.Connection.RemoteIpAddress;
        return View(model);
    }

    public Task<IActionResult>? DownloadFile(MappaModel model, EventArgs e)
    { 
        ViewBag.ipAddress = Request.HttpContext.Connection.RemoteIpAddress;
        return InvocatoDownloadFile?.Invoke(this, model, Request.HttpContext.Connection.RemoteIpAddress, e);
    }

    public void ExceptionHandler(string message, string? page = null)
    {
        TempData["ErrorMessage"] = message;
        if(page is not null) Response.Redirect(page);
    }
}

Views/Mappa/CaricaFile.cshtml
@model CaricaFileModel

@{
    ViewData["Title"] = "Carica un nuovo file a sistema";
}

<div class="text-center">
    <h1 class="display-4">@ViewData["Title"]</h1>

@using (Html.BeginForm("LoadFile", "Mappa", FormMethod.Post, new { enctype="multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <table class="center page">
        <tr>
            <td><label>(*) Codice stazione</label></td>
            <td>@Html.DropDownListFor(model => model.codiceStazione, Model.ListaStazioni)</td>
            <td>@Html.ValidationMessageFor(model => model.codiceStazione, "", new { @class = "text-danger" })</td>
        </tr>
        <tr>
            <td><label>(*) Data creazione<br>(YYYY-MM-DD HH:mm:ss)</label></td>
            <td>@Html.TextBoxFor(model => model.dataCreazione)</td>
            <td>@Html.ValidationMessageFor(model => model.dataCreazione, "", new { @class = "text-danger" })</td>
        </tr>
        <tr>
            <td><label>(*) Frequenza</label></td>
            <td>@Html.TextBoxFor(model => model.frequenza)</td>
            <td>@Html.ValidationMessageFor(model => model.frequenza, "", new { @class = "text-danger" })</td>
        </tr>
        <tr>
            <td><label>(*) Inizio periodo<br>(YYYY-MM-DD HH:mm:ss)</label></td>
            <td>@Html.TextBoxFor(model => model.inizioPeriodo)</td>
            <td>@Html.ValidationMessageFor(model => model.inizioPeriodo, "", new { @class = "text-danger" })</td>
        </tr>
        <tr>
            <td><label>(*) Fine periodo<br>(YYYY-MM-DD HH:mm:ss)</label></td>
            <td>@Html.TextBoxFor(model => model.finePeriodo)</td>
            <td>@Html.ValidationMessageFor(model => model.finePeriodo, "", new { @class = "text-danger" })</td>
        </tr>

        <tr>
            <td colspan=2>@Html.TextBoxFor(model => model.file, "", new { type= "file" })</td>
            @ViewBag.Message
            <td>@Html.ValidationMessageFor(model => model.file, "", new { @class = "text-danger" })</td>
        </tr>

        <tr>
            <td></td>
            <td><button type="submit" value="">Invia</button></td>
        </tr>
    </table>
}

</div>

@section Scripts{
    <script type="text/javascript">
        function openSuccessModal(strMessage){
            var myDiv = document.getElementById("MyModalSuccessAlertBody");
            myDiv.innerHTML = strMessage;
            $('#myModalSuccess').modal('show');
        }

        function openErrorModal(strMessage){
            var myDiv = document.getElementById("MyModalErrorAlertBody");
            myDiv.innerHTML = strMessage;
            $('#myModalError').modal('show');
        }

        $(document).ready(function() {
            var msgSucc = "@TempData["SuccessMessage"]";
            if(msgSucc) openSuccessModal(msgSucc);

            var msgErr = "@TempData["ErrorMessage"]";
            if(msgErr) openErrorModal(msgErr);
        });
    </script>
}

Views/Mappa/MappaStazioni.cshtml
@model MappaModel

@{
    ViewData["Title"] = "Mappa Stazioni";
}

<div class="text-center fullscreen">
    <h1 class="display-4">@ViewData["Title"]</h1>

    <div class="form-group">
        <table class="page">
            <tr><td></td><td>Stazioni</td><td style="text-align: center;">Dettagli Stazione</td>
            @if(Model.stazioneScelta is null){<td></td>}
            else {<td style="text-align:left">Elenco dei file per la stazione @Model.stazioneScelta</td>}
            </tr>
                
            <tr>
                <td style="vertical-align: top;">
                    <div>
                        <img src="@ViewBag.MapStationsData">
                    </div>
                </td>
                <td style="vertical-align: top;">
                @if(Model.ListaStazioni is not null)
                {
                    <table>
                    @foreach(var st in Model.ListaStazioni)
                    {
                        <tr>
                            <td><a href="@Url.Action("MappaStazioni", "Mappa", new { stazioneScelta = st.Key }  )"><button>@st.Key</button></a></td>
                        </tr>
                    }
                    </table>
                }
                </td>
                
                @if(Model._stazioneScelta is not null)
                {
                <td style="vertical-align: top; min-width:250px; text-align: center; padding:20px 20px;">
                    <label><h2>@Model._stazioneScelta.codice</h2></label><br>
                    <label>Nome:<b>@Model._stazioneScelta.nome</b></label><br>
                    <label>Rete:<b>@Model._stazioneScelta.rete</b></label><br>
                    <label>Tipo:<b>@Model._stazioneScelta.tipo</b></label><br>
                    <label>Latitudine:<b>@Model._stazioneScelta.latitudine</b></label><br>
                    <label>Longitudine:<b>@Model._stazioneScelta.longitudine</b></label><br>
                    <label>Altitudine:<b>@Model._stazioneScelta.altitudine</b></label><br>
                    <label>Gps:@if(Model._stazioneScelta.gps){<b>SI</b>}else{<b>NO</b>}</label><br>
                    <label>Galileo:@if(Model._stazioneScelta.galileo){<b>SI</b>}else{<b>NO</b>}</label><br>
                    <label>Glonass:@if(Model._stazioneScelta.glonass){<b>SI</b>}else{<b>NO</b>}</label><br><br>
                    <img src="@ViewBag.MapSingleStationData">
                </td>
                <td style="vertical-align: top;">
                    <table>
                    @foreach(var f in Model._stazioneScelta.elencoFileCaricati)
                    {
                        <tr>
                            <td><i class="fa fa-file-text-o" style="font-size:24px"></i></td>
                            <td>@f.Value</td>
                            <td>
                                @if(@GNSShare_client.client.GNSShare.endpoints(@ViewBag.ipAddress).Contains((int)@GNSShare_client.client.GNSShare.Operazioni.DOWNLOAD_FILE))
                                {   
                                <a href="@Url.Action("DownloadFile", "Mappa", new { stazioneScelta = Model._stazioneScelta.codice, fileScelto =  f.Value}  )"><i class="fa fa-download" style="font-size:24px"></i></a>
                                }
                            </td>
                        </tr>
                    }
                    </table>
                </td>
                }
            </tr>
        </table>
        
    </div>    

</div>
@section Scripts{
    <script type="text/javascript">
        function openSuccessModal(strMessage){
            var myDiv = document.getElementById("MyModalSuccessAlertBody");
            myDiv.innerHTML = strMessage;
            $('#myModalSuccess').modal('show');
        }

        function openErrorModal(strMessage){
            var myDiv = document.getElementById("MyModalErrorAlertBody");
            myDiv.innerHTML = strMessage;
            $('#myModalError').modal('show');
        }

        $(document).ready(function() {
            var msgSucc = "@TempData["SuccessMessage"]";
            if(msgSucc) openSuccessModal(msgSucc);

            var msgErr = "@TempData["ErrorMessage"]";
            if(msgErr) openErrorModal(msgErr);
        });
    </script>
}